spring:
  datasource:
    url: jdbc:mysql://localhost:3306/server
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
    show-sql: true